### ISSUE TITLE
Base frequency calculations

### ISSUE THREAD

**Issue by roblanf** [Tagliacollo/PartitionUCE#1]
On line 33 in functions.py, you should not be using the length of the alignment as the denominator, because this will not account for gaps, N's, and other non-ACGT characters.

Instead, you need a three-step process. 
1. Get your counts of ACGT. 
2. Sum them to get the denominator
3. Divide the counts by the sum to get the frequencies. 

This is a clean way of ignoring (intentionally) gaps etc. when calculating your base frequencies.

**Comment by Tagliacollo** [comment]
I improved the function bp_freqs_calc. It looks much better now (thanks to you!!!). Let me know what you think

**Comment by roblanf** [comment]
Once it's done, you can close it... :)
