### ISSUE TITLE
central site method

### ISSUE THREAD

**Issue by roblanf** [Tagliacollo/PartitionUCE#17]
The idea here is to write a function that groups together sites based on their physical position in the UCE.

I.e., we put all the central sites into one partition, and all the sites one to the right of the central site in one partition, and all the sites one to the left of the central site in one partition, etc.

So the character sets might look like:

minus_10 = 100, 500, 900;
minus_9 = 101, 501, 901;
...
central = 110, 510, 910;
plus_1 = 111, 511, 911;

The second part of this is to decide what to do with small subsets. As long as there are >100 UCEs, the central partition and those near it will have >100 sites. But at some point we'll end up with partitions with less than 100 sites.

My suggestion is to first write the algorithm to produce the charactersets above, without worrying about size. I'd make this a list of sets. 

Then, I'd write an algorithm that ran over that list of sets making sure in some sensible way that all sets were bigger than some sensible size, like at least 100 sites. E.g. you could start at the outside edges of the list, working your way in by joining sets that are <100 sites with the set closer to the middle.

**Comment by Tagliacollo** [comment]
issue solved!
