### ISSUE TITLE
optional (minor) improvement to bp_calc function

### ISSUE THREAD

**Issue by roblanf** [Tagliacollo/PartitionUCE#2]
Your function is fine, and it works. I have two suggestions though:
1. Make the bp order alphabetical
2. You could make it slightly more intuitive like this (perhaps) but it makes basically no difference:

``` python
bp_counts = np.array([A, C, G, T])

bp_freqs = bp_counts/float(sum(bp_counts))

```

I'm not even sure this is better. But since you asked, there is what I would have done.

**Comment by Tagliacollo** [comment]
done =)
