### ISSUE TITLE
permutations

### ISSUE THREAD

**Issue by roblanf** [Tagliacollo/PartitionUCE#20]
to check if any of our approaches really work, we need to do permutations.

i.e., we do 20 permutations where we shuffled the columns within each UCE. We then ask whether the observed (i.e. unshuffled) AICc is really better than the 20 permutations. If our approach is really making biologically sound inferences, then we expect this to be the case. It might not be the case though, e.g. if our AICc scores are better than partitioning by UCE just because our approach defines 3x more data blocks.

**Comment by Tagliacollo** [comment]
done
