### ISSUE TITLE
double check multinomial calculations

### ISSUE THREAD

**Issue by roblanf** [Tagliacollo/PartitionUCE#24]
We rely on getting these right. The challenge is to find at least one independent implementation (e.g. I think there's on in R) and plug in some example site- and background- base frequencies, to make sure our calculations are correct!

Doing a few on paper would be good too. 

So, here are a few to try, can you get results on paper, using independent code, and using our code, and post them below (then we'll really know if we're right and possibly why we're not...):

```
1. background freqs: [0.25, 0.25, 0.25, 0.25]

site freqs:
[0.25, 0.25, 0.25, 0.25]
[0, 0, 0, 0] # hmmm
[0.00, 0.00, 0.5, 0.5]
[0.1, 0.2, 0.3, 0.4]

2. background freqs: [0.0, 0.0, 0.5, 0.5]

same site freqs as above

3. background freqs: [0.1, 0.2, 0.3, 0.4]

same site freqs as above
```

**Comment by Tagliacollo** [comment]
I posted the results (and R script) of our test analyses. The results came out as predicted, except in one test matrix. Not sure whether my predictions were wrong or it's a bug in the code. I'd like to show you the results and have a chat before proceeding with the server.

**Comment by Tagliacollo** [comment]
nevermind, my predictions were wrong about the results of full multi. I'm performing new analyses and making new predictions. My mistake was that I forgot to take into account the minimum window size. My prediction was that the results of multi and full multi should be identical. They are actually identical if the minimum window size is equal to the size of the matrix (so we have just one background freqs, correct?). If I change the minimum window size, results can be equal (when base counts and background freqs are similar) or different  (when one of the two described before is different). new results coming soon

**Comment by roblanf** [comment]
OK - it's good if our code gets consistent answers. 

The next question is whether our code gets the same answers as other multinomial likelihood implementations. For that you'll need to do the calculations in another piece of software, either with an independently-written python implementation (i.e. NOT written by us) or an implementation in somethign like R.

My understanding is that there's an existing R package that will calculate multinomial likelihoods, but I don't know what it is...

R

**Comment by roblanf** [comment]
Also, while we're on the subject, we might find that our likelihoods are inaccurate because of the factorials (they're so big). If this is the case, the beginning of a solution is here:

http://stats.stackexchange.com/questions/65939/multinomial-likelihood-for-large-number-of-groups
